import { Component, OnInit } from '@angular/core';
import { filter, interval, map } from 'rxjs';

@Component({
  selector: 'app-operator-basic',
  templateUrl: './operator-basic.component.html',
  styleUrls: ['./operator-basic.component.css']
})
export class OperatorBasicComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  const newObservable=interval(1000)
  newObservable.subscribe(data=>{
    if(data%2===0){
      
      console.log('Even number '+ data)

    }
  })
  // these thing i can also do through rxjs operaote 

  newObservable.pipe(
    filter((x)=>{
      return x%2===0
      }
      ),
    map(number=>{
    console.log('the number that is generated by Rxjs operaotr '+ number)
    })
    
  )
  .subscribe(data=>{
    console.log(data)
  })
  }

}
